version: '3'

services:
    main:
        build: .
        image: lexonomy
        volumes:
            - siteconfig.json:/home/script/Documents/lexonomy-master/website/siteconfig.json
            - data:/home/script/Documents/lexonomy-master/data

        ports:
            - "8000:8000"

volumes:
  siteconfig.json:
  data:
    
